language: android
android:
  components:
  - tools
  - platform-tools
env:
  global:
    secure: bIgCYGbJqQxMD3KvpveVTLdeXOG6Ug8QgwiAjpmQugR5uBmO9UwpJBdZ04mt2UUDEzZHLuCQeGIBrKWkIVMbxc/hA7VTHrT2KB8SZbmoDt1VsmEyHrI4zWozr4ERYq099/Xf+Kz2w0woyNwjJnkZZkGWfXdi4O5qBOEzwsHZfx20Wk9kf4H/6XygDnGmqqPitZ6ogw9dFCKPisoQ+hkHsjWIZzZOHba6LRpaQJ8dF4BgyKyBsSchtBuJ8EnHNOBcq0h5iSA5QAbDEXEdG27ieMW+WVeTfVFVps9VNIb0s9M/Vx1R8sEhcMAV+KByLNfJxWSYsQRZoCPWN3uqI49CTZXnVO7pGNdvC/+T2y/TzRmV8E6xf7mB3cSu5bkU5ictCqMYoJZu06k1eA3bO/YL90w1w2f/WR2lIO/cBUpAeuK4wDUQxQMYNtR/wXZw2CaVKJO2d9Nhmc3rRDkmLFox5445r+cPLGnnSbX5aK9Sfflb1TWqzjABlMBrJDcBPgPd5S/3P+A+hAG+EBE5SDibx/OLeWi+vquue479Xgu4Brutfw1BfekeLm7MaCrzJ05vMWhNbNAk7qTiaybo3WcpSdjy3Uu98BnfaUk3J0xydZDrt0lS1CnTlAmfKI5kAtg4OZlbvuTj9jG+BmOzIybMEbQphtI+1TIWnlqi2UgUIHo=

before_install:
- export LANG=en_US.UTF-8
- npm install -g npm@5.6.0
- openssl aes-256-cbc -K $encrypted_6f938e004816_key -iv $encrypted_6f938e004816_iv
  -in dm-shield.keystore.enc -out dm-shield.keystore -d

script:
- npm install
- ionic build cordova android --release
- jarsigner -verbose -sigalg SHA1withRSA -storepass $my_password -keypass $my_password -digestalg SHA1 -keystore dm-shield.keystore platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk MY_KEYSTORE_ALIAS
- zipalign -v 4 platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk platforms/android/app/build/outputs/apk/release/app-release-signed.apk
- supply run -j platforms/android/gapi.json -p com.github.disparter.dm_shield -b platforms/android/app/build/outputs/apk/release/app-release-signed.apk
